### Modem Configs
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/config/modem/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/modem.conf \
    $(DEVICE_PATH)/config/modem/2/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/2/modem.conf \
    $(DEVICE_PATH)/config/modem/3/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/3/modem.conf \
    $(DEVICE_PATH)/config/modem/10/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/10/modem.conf \
    $(DEVICE_PATH)/config/modem/11/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/11/modem.conf \
    $(DEVICE_PATH)/config/modem/13/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/13/modem.conf \
    $(DEVICE_PATH)/config/modem/14/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/14/modem.conf \
    $(DEVICE_PATH)/config/modem/34/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/34/modem.conf \
    $(DEVICE_PATH)/config/modem/37/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/37/modem.conf \
    $(DEVICE_PATH)/config/modem/38/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/38/modem.conf \
    $(DEVICE_PATH)/config/modem/39/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/39/modem.conf \
    $(DEVICE_PATH)/config/modem/40/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/40/modem.conf \
    $(DEVICE_PATH)/config/modem/41/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/41/modem.conf \
    $(DEVICE_PATH)/config/modem/42/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/42/modem.conf \
    $(DEVICE_PATH)/config/modem/71/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/71/modem.conf \
    $(DEVICE_PATH)/config/modem/88/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/88/modem.conf \
    $(DEVICE_PATH)/config/modem/122/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/122/modem.conf \
    $(DEVICE_PATH)/config/modem/132/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/132/modem.conf \
    $(DEVICE_PATH)/config/modem/133/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/133/modem.conf \
    $(DEVICE_PATH)/config/modem/134/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/134/modem.conf \
    $(DEVICE_PATH)/config/modem/170/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/170/modem.conf \
    $(DEVICE_PATH)/config/modem/177/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/177/modem.conf \
    $(DEVICE_PATH)/config/modem/184/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/184/modem.conf \
    $(DEVICE_PATH)/config/modem/191/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/191/modem.conf \
    $(DEVICE_PATH)/config/modem/192/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/192/modem.conf \
    $(DEVICE_PATH)/config/modem/193/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/193/modem.conf \
    $(DEVICE_PATH)/config/modem/196/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/196/modem.conf \
    $(DEVICE_PATH)/config/modem/197/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/197/modem.conf \
    $(DEVICE_PATH)/config/modem/198/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/198/modem.conf \
    $(DEVICE_PATH)/config/modem/202/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/202/modem.conf \
    $(DEVICE_PATH)/config/modem/236/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/236/modem.conf \
    $(DEVICE_PATH)/config/modem/241/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/241/modem.conf \
    $(DEVICE_PATH)/config/modem/244/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/244/modem.conf \
    $(DEVICE_PATH)/config/modem/272/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/272/modem.conf \
    $(DEVICE_PATH)/config/modem/273/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/273/modem.conf \
    $(DEVICE_PATH)/config/modem/274/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/274/modem.conf \
    $(DEVICE_PATH)/config/modem/286/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/286/modem.conf \
    $(DEVICE_PATH)/config/modem/297/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/297/modem.conf \
    $(DEVICE_PATH)/config/modem/298/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/298/modem.conf \
    $(DEVICE_PATH)/config/modem/299/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/299/modem.conf \
    $(DEVICE_PATH)/config/modem/300/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/300/modem.conf \
    $(DEVICE_PATH)/config/modem/303/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/303/modem.conf \
    $(DEVICE_PATH)/config/modem/306/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/306/modem.conf \
    $(DEVICE_PATH)/config/modem/310/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/310/modem.conf \
    $(DEVICE_PATH)/config/modem/311/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/311/modem.conf \
    $(DEVICE_PATH)/config/modem/326/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/326/modem.conf \
    $(DEVICE_PATH)/config/modem/350/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/350/modem.conf \
    $(DEVICE_PATH)/config/modem/384/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/384/modem.conf \
    $(DEVICE_PATH)/config/modem/404/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/404/modem.conf \
    $(DEVICE_PATH)/config/modem/415/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/415/modem.conf \
    $(DEVICE_PATH)/config/modem/420/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/420/modem.conf \
    $(DEVICE_PATH)/config/modem/421/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/421/modem.conf \
    $(DEVICE_PATH)/config/modem/424/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/424/modem.conf \
    $(DEVICE_PATH)/config/modem/432/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/432/modem.conf \
    $(DEVICE_PATH)/config/modem/433/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/433/modem.conf \
    $(DEVICE_PATH)/config/modem/434/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/434/modem.conf \
    $(DEVICE_PATH)/config/modem/436/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/436/modem.conf \
    $(DEVICE_PATH)/config/modem/437/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/437/modem.conf \
    $(DEVICE_PATH)/config/modem/438/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/438/modem.conf \
    $(DEVICE_PATH)/config/modem/439/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/439/modem.conf \
    $(DEVICE_PATH)/config/modem/441/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/441/modem.conf \
    $(DEVICE_PATH)/config/modem/442/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/442/modem.conf \
    $(DEVICE_PATH)/config/modem/446/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/446/modem.conf \
    $(DEVICE_PATH)/config/modem/456/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/456/modem.conf \
    $(DEVICE_PATH)/config/modem/458/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/458/modem.conf \
    $(DEVICE_PATH)/config/modem/460/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/460/modem.conf \
    $(DEVICE_PATH)/config/modem/461/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/461/modem.conf \
    $(DEVICE_PATH)/config/modem/465/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/465/modem.conf \
    $(DEVICE_PATH)/config/modem/466/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/466/modem.conf \
    $(DEVICE_PATH)/config/modem/468/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/468/modem.conf \
    $(DEVICE_PATH)/config/modem/469/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/469/modem.conf \
    $(DEVICE_PATH)/config/modem/473/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/473/modem.conf \
    $(DEVICE_PATH)/config/modem/483/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/483/modem.conf \
    $(DEVICE_PATH)/config/modem/489/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/489/modem.conf \
    $(DEVICE_PATH)/config/modem/492/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/492/modem.conf \
    $(DEVICE_PATH)/config/modem/503/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/503/modem.conf \
    $(DEVICE_PATH)/config/modem/513/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/513/modem.conf \
    $(DEVICE_PATH)/config/modem/528/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/528/modem.conf \
    $(DEVICE_PATH)/config/modem/530/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/530/modem.conf \
    $(DEVICE_PATH)/config/modem/549/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/549/modem.conf \
    $(DEVICE_PATH)/config/modem/611/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/611/modem.conf \
    $(DEVICE_PATH)/config/modem/902/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/902/modem.conf \
    $(DEVICE_PATH)/config/modem/903/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/903/modem.conf \
    $(DEVICE_PATH)/config/modem/905/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/905/modem.conf \
    $(DEVICE_PATH)/config/modem/906/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/906/modem.conf \
    $(DEVICE_PATH)/config/modem/908/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/908/modem.conf \
    $(DEVICE_PATH)/config/modem/909/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/909/modem.conf \
    $(DEVICE_PATH)/config/modem/911/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/911/modem.conf \
    $(DEVICE_PATH)/config/modem/913/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/913/modem.conf \
    $(DEVICE_PATH)/config/modem/915/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/915/modem.conf \
    $(DEVICE_PATH)/config/modem/916/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/916/modem.conf \
    $(DEVICE_PATH)/config/modem/918/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/918/modem.conf \
    $(DEVICE_PATH)/config/modem/921/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/921/modem.conf \
    $(DEVICE_PATH)/config/modem/923/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/923/modem.conf \
    $(DEVICE_PATH)/config/modem/925/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/925/modem.conf \
    $(DEVICE_PATH)/config/modem/927/modem.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/customization/modem/927/modem.conf
